### PR TITLE
Fix code style issues

### LINKED ISSUE #292: Fix code style issues
There are some issues with the codebase that would be nice to fix:

 * Code style is inconsistent
   - E.g. some places use `x == null` or `x != null` instead of `x is null` and `x is not null`
   - Some places are missing braces around their bodies (like `if`s and other control statements)

There are likely other similar issues given that the code has lived for quite some time by now.

### PR DESCRIPTION
**Pull request by fasetto**
Fixed some code style issues. Closes: #292

### CODE REVIEW

File: src/Colore/Native/NativeSdkMethods.cs [hunk 1]
```diff
@@ -160,7 +160,7 @@ internal NativeSdkMethods()
             [In] Guid deviceId,
             [In] Effects.Generic.EffectType effectType,
             [In] IntPtr param,
-            [In] [Out] ref Guid effectId);
```
Comment (Sharparam) [inline src/Colore/Native/NativeSdkMethods.cs]: The space between attributes should be left intact.
(If this change was automated based on the included code style settings file for ReSharper then that's a miss on my part.)

File: tests/Colore.Tests/Data/ColorTests.cs [hunk 2]
```diff
@@ -229,8 +229,8 @@ public void ShouldNotEqualNull()
         {
             var c = new Color(255, 255, 255);
             Assert.AreNotEqual(c, null);
-            Assert.False(c == null);
-            Assert.True(c != null);
```
Comment (Sharparam) [inline tests/Colore.Tests/Data/ColorTests.cs]: For the `Assert` calls in test files, leave the `==` and `!=` as is, since these are testing operators defined on the types, and `is` / `is not` will bypass them.

**Review by Sharparam — CHANGES_REQUESTED** [review]
Nice work! This helps a lot in bringing the code style up to par.

A couple things to fix as noted in the review comments, and then it should be good to merge :)

Edit: Oh, also: blank line after closing braces. You can see StyleCop outlining the places in the CI log here: https://github.com/chroma-sdk/Colore/runs/3788689815#step:8:553

File: src/Colore/Native/NativeSdkMethods.cs (hunk 1 above)
Comment (fasetto) [reply src/Colore/Native/NativeSdkMethods.cs]: I am using vscode. Default formatter does that. I don't know how can I change that. Right now I am fixing manually. /:

Comment (Sharparam) [reply src/Colore/Native/NativeSdkMethods.cs]: Ah I see, yeah I'm not sure if there's something to configure how VSCode formats it.

**Review by Sharparam — APPROVED** [review]

**Comment by Sharparam** [comment]
Thank you for the contribution! :)
